# Задание №1
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
pip install numpy

In [1]:
import numpy as np

In [90]:
x = np.arange(10)
x = x[::-1]
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [2]:
t = np.arange(25).reshape(5,5)
t = t[::-1]
t

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [3]:
t.diagonal() #извлекает значения по диагонали

array([20, 16, 12,  8,  4])

In [4]:
sum(t.diagonal()) # сумма значений по диагонали


60

# возможен второй вариант решения

In [54]:
d = np.diag(np.arange(20, 0, -2))
d

array([[20,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 16,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 14,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 12,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 10,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  6,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  2]])

In [57]:
sum(d.diagonal())

110

# Задание №3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [7]:
a = np.array([[4,2,1],[1,3,0],[0,5,4]])

In [8]:
b = np.array([4,12,-3])

In [5]:
from numpy import linalg

In [9]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

# Задача 4 домашнего задания
Имеется матрица покупок в интернет-магазине. 
Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [2]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
users_stats

array([[2, 1, 0, 0, 0, 0],
       [1, 1, 2, 1, 0, 0],
       [2, 0, 1, 0, 0, 0],
       [1, 1, 2, 1, 0, 1],
       [0, 0, 1, 2, 0, 0],
       [0, 0, 0, 0, 0, 5],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 3],
       [1, 0, 0, 2, 1, 4]])

In [ ]:
На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [3]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
next_user_stats

array([0, 1, 2, 0, 0, 0])

In [ ]:
Найдите самого похожего пользователя. 
Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats


In [4]:
for user in users_stats:
    userLenght = np.linalg.norm(user)
    next_user_statsLenght = np.linalg.norm(next_user_stats)
    print(np.dot(user,next_user_stats) / (userLenght * next_user_statsLenght))



0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0
